name: Deploy Node Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} -t b0bwen/rental-app-server ./server

      - name: Publish Image to Docker Hub
        run: docker push b0bwen/rental-app-server:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull b0bwen/rental-app-server:latest

      - name: Delete old container
        run: docker rm -f rental-app-server-container || true

      - name: Create .env file
        run: |
          cat <<EOF > .env
          DATABASE_URL=${{ secrets.DATABASE_URL }}

          CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}
          EOF

      - name: Run Docker Container with .env
        run: |
          docker run -d --env-file .env -p 4001:4000 --name rental-app-server-container b0bwen/rental-app-server

      - name: Run Prisma Migrations
        run: |
          docker exec rental-app-server-container npx prisma migrate deploy
